//
//  Mocks.swift
//  ChefWebOntology
//
//  Created by Monika Mateska on 3.7.21.
//

import Foundation

class Mocks {
    static var chef = ChefModel(name: "Gordon James Ramsay",
                                photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Gordon_Ramsay.jpg/300px-Gordon_Ramsay.jpg",
                                birthDate: "08.11.1966",
                                birthPlace: "Johnstone",
                                website: "https://www.gordonramsay.com",
                                ratings: ["Michelin Stars",
                                          "The Good Food Guide"],
                                tvShows: ["Gordon's Great Escape",
                                          "Gordon Behind Bars",
                                          "Gordon Ramsay's 24 Hours to Hell and Back",
                                          "Kitchen Nightmares",
                                          "Love'sKitchen"],
                                ownerOf: [RestaurantModel(name: "Union Street Café",
                                                          country: "United Kingdom",
                                                          description: "Union Street Café is a restaurant, owned by chef Gordon Ramsay, in Southwark, London. It was the first of Ramsay's restaurants to be opened without the involvement of Chris Hutchinson, and at one point was backed by footballer David Beckham. The Café serves Mediterranean cuisine, with mostly Italian dishes. The head chef, , designs the menu, which is changed daily. Before the Café was opened, it received more than 10,000 booking requests, with seating filled to the end of the year. Food critics' reviews have been mixed, with differing opinions of the veal saltimbocca but agreement in dislike of a dish of octopus, borlotti bean, and 'nduja sausage.",
                                                          website: nil),
                                          RestaurantModel(name: "Bread Street Kitchen - Singapore",
                                                          country: "Singapore",
                                                          description: "Bread Street Kitchen is a restaurant owned by celebrity chef and restaurateur Gordon Ramsay. Located in Singapore and modelled after the original Bread Street Kitchen in the United Kingdom, the restaurant was opened in June 2015.",
                                                          website: "https://www.gordonramsayrestaurants.com/bread-street-kitchen-singapore/%7COfficial"),
                                          RestaurantModel(name: "Gordon Ramsay Plane Food",
                                                          country: "United Kingdom",
                                                          description: "Gordon Ramsay Plane Food is a restaurant owned by chef Gordon Ramsay and located within Terminal 5 of Heathrow Airport, London. The restaurant cost £2.5 million to build and is located within the airside area of the airport. It opened in 2008 alongside the rest of Terminal 5, and with several other Ramsay-related openings that year. Ramsay said that he aimed to keep the menu lean without the use of heavy sauces, and menus are also offered for quick dining as well as takeaway cool boxes which contain a three course meal to be eaten on a plane. Critics have been mostly positive, although one initial poor review by Jan Moir was picked up by the mainstream media. The concept of the cool boxes was also praised. It was Ramsay's first airport-based restaurant, and in 2013 he announced that he was planning to take the concept to a number of airports within the United States. ",
                                                          website: nil),
                                          RestaurantModel(name: "Bread Street Kitchen and Bar - Hong Kong",
                                                          country: "Hong Kong",
                                                          description: "Bread Street Kitchen and Bar, Hong Kong is a restaurant and bar located at Shop G02, G/F, The Peak Galleria, 118 Peak Road, Hong Kong and is operated by Gordon Ramsay",
                                                          website: "https://www.gordonramsayrestaurants.com/bread-street-kitchen-and-bar-hong-kong/%7COfficial"),
                                          RestaurantModel(name: "Le Pressoir d'Argent",
                                                          country: "United Kingdom",
                                                          description: "Le Pressoir d'Argent is a two Michelin star restaurant owned by British celebrity chef and restaurateur Gordon Ramsay located in Bordeaux, France. It opened in 2015 and was Ramsay's second restaurant in France. ",
                                                          website: "https://www.gordonramsayrestaurants.com/plane-food/"),
                                          RestaurantModel(name: "Maze Grill Royal Hospital Road",
                                                          country: "United Kingdom",
                                                          description: "Maze Grill Royal Hospital Road (stylised as maze Grill Royal Hospital Road and formerly Foxtrot Oscar) is a restaurant in Chelsea, London, England owned by celebrity chef and restaurateur Gordon Ramsay. ",
                                                          website: nil)],
                                cuisines: [CuisineModel(name: "French cuisine",
                                                        chefNames: ["Dominique Crenn",
                                                                    "Gordon Ramsay",
                                                                    "Gray Kunz",
                                                                    "Alain Ducasse",
                                                                    "Alain Roux",
                                                                    "Alexis Gauthier",
                                                                    "Cheryl Koh",
                                                                    "Simon Gault",
                                                                    "George Calombaris",
                                                                    "Gilbert Le Coze"],
                                                        description: "French cuisine consists of the cooking traditions and practices from France. French cuisine developed throughout the centuries influenced by the many surrounding cultures of Spain, Italy, Switzerland, Germany and Belgium, in addition to its own food traditions on the long western coastlines of the Atlantic, the Channel and of course inland. In the 14th century, Guillaume Tirel, a court chef known as \"Taillevent\", wrote Le Viandier, one of the earliest recipe collections of medieval France. In the 17th century, chefs François Pierre La Varenne and Marie-Antoine Carême spearheaded movements that shifted French cooking away from its foreign influences and developed France's own indigenous style. Cheese and wine are a major part of the cuisine. They play different roles regionally and nationally, with many variations and appellation d'origine contrôlée (AOC) (regulated appellation) laws. French cuisine was made important in the 20th century by Auguste Escoffier to become the modern haute cuisine; Escoffier, however, left out much of the local culinary character to be found in the regions of France and was considered difficult to execute by home cooks. Culinary tourism and the Guide Michelin helped to acquaint people with the cuisine bourgeoise of the urban elites and the peasant cuisine of the French countryside starting in the 20th century. Gascon cuisine has also had great influence over the cuisine in the southwest of France. Many dishes that were once regional have proliferated in variations across the country. Knowledge of French cooking has contributed significantly to Western cuisines. Its criteria are used widely in Western cookery school boards and culinary education. In November 2010, French gastronomy was added by the UNESCO to its lists of the world's \"intangible cultural heritage\""),
                                           CuisineModel(name: "Italian cuisine",
                                                        chefNames: ["Umberto Bombana",
                                                                    "Marco Canora",
                                                                    "Gordon Ramsay",
                                                                    "Aktar Islam",
                                                                    "Aldo Zilli",
                                                                    "Alessandro Borghese",
                                                                    "Cesare Casella",
                                                                    "Chef Jolly",
                                                                    "Mario Frittoli",
                                                                    "Gennaro Contaldo"],
                                                        description: "Italian cuisine is a Mediterranean cuisine consisting of the ingredients, recipes and cooking techniques developed across the Italian Peninsula since the antiquity, and later spread around the world together with waves of Italian diaspora. Italian cuisine is generally characterized by its simplicity, with many dishes having only two to four main ingredients. Italian cooks rely chiefly on the quality of the ingredients rather than on elaborate preparation. Ingredients and dishes vary by region. Many dishes that were once regional have proliferated with variations throughout the country."),
                                           CuisineModel(name: "British cuisine",
                                                        chefNames: ["Gordon Ramsay",
                                                                    "Ethel G. Hofman",
                                                                    "Aktar Islam",
                                                                    "Robert Thompson (chef)",
                                                                    "Alastair Little",
                                                                    "Gary Rhodes",
                                                                    "Kenny Atkinson (chef)",
                                                                    "Lisa Goodwin Allen",
                                                                    "Frances Atkins",
                                                                    "Jamie Oliver"],
                                                        description: "British cuisine is the heritage of cooking traditions and practices associated with the United Kingdom. Although Britain has a rich indigenous culinary tradition, its colonial history has profoundly enriched its native cooking traditions. British cuisine absorbed the cultural influences of its post-colonial territories – in particular those of South Asia. In ancient times Celtic agriculture and animal breeding produced a wide variety of foodstuffs for the indigenous Celts and Britons. Anglo-Saxon England developed meat and savoury herb stewing techniques before the practice became common in Europe. The Norman conquest introduced exotic spices into England in the Middle Ages. The British Empire facilitated a knowledge of Indian cuisine with its \"strong, penetrating spices and herbs\". Food rationing policies put into place by the British government during the wartime periods of the 20th century are widely considered today to be responsible for British cuisine's poor international reputation. Well-known traditional British dishes include full breakfast, fish and chips, the Christmas dinner, the Sunday roast, steak and kidney pie, shepherd's pie, and bangers and mash. People in Britain, however, eat a wide variety of foods based on the cuisines of Europe, India, and other parts of the world. British cuisine has many regional varieties within the broader categories of English, Scottish and Welsh cuisine and Northern Irish cuisine. Each has developed its own regional or local dishes, many of which are geographically indicated foods such as Cornish pasties, the Yorkshire pudding, Cumberland Sausage, Arbroath Smokie, and Welsh cakes.")],
                                books: [BookModel(name: "Gordon Ramsay's Ultimate Fit Food",
                                                  description: "Gordon Ramsay's Ultimate Fit Food is a cookbook written by chef Gordon Ramsay. The book is collection of food recipes for the purpose of cooking and eating. The book has three sections namely ′Healthy′, ′Lean recipes′ and ′Fit′, each consisting of breakfasts, lunches, suppers, sides and snacks' recipes with health-boosting benefits explained.",
                                                  website: "https://www.gordonramsay.com/gr/recipes/books/",
                                                  published: "23.05.1998")])
}
